### ISSUE TITLE
Acquired spectrum has bad date

### ISSUE THREAD

**Issue by christophkern** [NOVACProject/MobileDOAS#86] opened 2018-07-11 03:46 UTC
Every so often, a spectrum is saved with a bad date. Usually, only one such spectrum is written, and the following one is fine again. 
In my example measurement, all spectra are good up to 436. Spectrum 437 has a bad date in the STD file. Spectrum 438 is fine again.
This issue has occurred several times now - perhaps a bad GPS point? But strange that it always seems to be just one spectrum that is affected, not several in a row.
The attached std spectra have been renamed to *.txt in order to allow uploading to github.

[00436_0.STD.txt](https://github.com/NOVACProject/MobileDOAS/files/2182864/00436_0.STD.txt)

[00437_0.STD.txt](https://github.com/NOVACProject/MobileDOAS/files/2182865/00437_0.STD.txt)

[00438_0.STD.txt](https://github.com/NOVACProject/MobileDOAS/files/2182863/00438_0.STD.txt)

**Comment by dnorgaard-usgs** [comment] 2018-07-19 21:40
The code was modified to read the date from GPS as an int instead of string.  This simplifies the code quite a bit.  It is also more consistent with how the time is read (into a long), and there have not been any reported cases of bad time in the STD files (to my knowledge).  In theory, non-alphanumeric characters would not parse into int and would not get read into the date field.   So far the date is writing as before, but since this error does not occur often and cannot be reproduced, it cannot be said for certain this fixes this bug.

The date appears to be used only in the spectrum files.

**Comment by dnorgaard-usgs** [comment] 2018-07-19 21:46
Will reopen if problem persist.

**Comment by dnorgaard-usgs** [comment] 2019-02-02 00:51
The potential fix previously submitted causes a serious bug in that the date can be improperly decoded for writing into STD files if a potential 5 digit integer date (e.g. 20219) is not padded with zero first.  It could be that the data can be read as int still from GPS but care must be taken to store in string as 6 characters.  For now I am just going to revert this change.

**Comment by dnorgaard-usgs** [comment] 2019-02-06 16:12
Mattias committed some code changes yesterday that read the date as long and convert to 6 character string.  (Along with some other improvements surrounding the handling of date.)  This should, in theory, fix this issue.

**Closed** 2019-02-07 15:20 UTC
Labels: bug
